DROP TABLE IF EXISTS stacks;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS api_tokens;
DROP TABLE IF EXISTS organization_members;
DROP TABLE IF EXISTS organizations;
DROP TABLE IF EXISTS users;
