// Code generated by tygo. DO NOT EDIT.
// Generated by tygo from github.com/pulumi/pulumi/sdk/v3/go/common/apitype
// Pulumi SDK v3.226.0 — DO NOT EDIT manually.
// To regenerate: bun run types:generate

//////////
// source: cli.go

/**
 * CLIVersionResponse is the response from the server with information about CLI versions.
 */
export interface CLIVersionResponse {
	latestVersion: string;
	oldestWithoutWarning: string;
	latestDevVersion: string;
}

//////////
// source: core.go
/*
Package apitype contains the full set of "exchange types" that are serialized and sent across separately versionable
boundaries, including service APIs, plugins, and file formats.  As a result, we must consider the versioning impacts
for each change we make to types within this package.  In general, this means the following:

 1. DO NOT take anything away
 2. DO NOT change processing rules
 3. DO NOT make optional things required
 4. DO make anything new be optional

In the event that this is not possible, a breaking change is implied.  The preferred approach is to never make
breaking changes.  If that isn't possible, the next best approach is to support both the old and new formats
side-by-side (for instance, by using a union type for the property in question).
*/

/**
 * DeploymentSchemaID is the $id for the deployment schema.
 */
export const DeploymentSchemaID = "https://github.com/pulumi/pulumi/blob/master/sdk/go/common/apitype/deployments.json";
/**
 * ResourceSchemaID is the $id for the deployment schema.
 */
export const ResourceSchemaID = "https://github.com/pulumi/pulumi/blob/master/sdk/go/common/apitype/resources.json";
/**
 * PropertyValueSchemaID is the $id for the property value schema.
 */
export const PropertyValueSchemaID = "https://github.com/pulumi/pulumi/blob/master/sdk/go/common/apitype/property-values.json";
/**
 * DeploymentSchemaVersionCurrent is the current version of the `Deployment` schema
 * when not using features that require v4.
 */
export const DeploymentSchemaVersionCurrent = 3;
/**
 * DeploymentSchemaVersionLatest is the latest version of the `Deployment` schema, when
 * using features that require v4.
 */
export const DeploymentSchemaVersionLatest = 4;
export type DeploymentSchemaVersion = typeof DeploymentSchemaVersionCurrent | typeof DeploymentSchemaVersionLatest;
/**
 * VersionedCheckpoint is a version number plus a json document. The version number describes what
 * version of the Checkpoint structure the Checkpoint member's json document can decode into.
 */
export interface VersionedCheckpoint {
	version: number /* int */;
	/**
	 * Features contains an optional list of features used by this Checkpoint. The CLI will error when reading a
	 * Checkpoint that uses a feature that is not supported by that version of the CLI. This is only looked at
	 * when `Version` is 4 or greater.
	 */
	features?: string[];
	checkpoint: unknown;
}
/**
 * CheckpointV1 is a serialized deployment target plus a record of the latest deployment.
 */
export interface CheckpointV1 {
	/**
	 * Stack is the stack to update.
	 */
	stack: string;
	/**
	 * Config contains a bag of optional configuration keys/values.
	 */
	config?: Record<string, unknown>;
	/**
	 * Latest is the latest/current deployment (if an update has occurred).
	 */
	latest?: DeploymentV1;
}
/**
 * CheckpointV2 is the second version of the Checkpoint. It contains a newer version of
 * the latest deployment.
 */
export interface CheckpointV2 {
	/**
	 * Stack is the stack to update.
	 */
	stack: string;
	/**
	 * Config contains a bag of optional configuration keys/values.
	 */
	config?: Record<string, unknown>;
	/**
	 * Latest is the latest/current deployment (if an update has occurred).
	 */
	latest?: DeploymentV2;
}
/**
 * CheckpointV3 is the third version of the Checkpoint. It contains a newer version of
 * the latest deployment.
 */
export interface CheckpointV3 {
	/**
	 * Stack is the stack to update.
	 */
	stack: string;
	/**
	 * Config contains a bag of optional configuration keys/values.
	 */
	config?: Record<string, unknown>;
	/**
	 * Latest is the latest/current deployment (if an update has occurred).
	 */
	latest?: DeploymentV3;
}
/**
 * DeploymentV1 represents a deployment that has actually occurred. It is similar to the engine's snapshot structure,
 * except that it flattens and rearranges a few data structures for serializability.
 */
export interface DeploymentV1 {
	/**
	 * Manifest contains metadata about this deployment.
	 */
	manifest: ManifestV1;
	/**
	 * Resources contains all resources that are currently part of this stack after this deployment has finished.
	 */
	resources?: ResourceV1[];
}
/**
 * DeploymentV2 is the second version of the Deployment. It contains newer versions of the
 * Resource API type.
 */
export interface DeploymentV2 {
	/**
	 * Manifest contains metadata about this deployment.
	 */
	manifest: ManifestV1;
	/**
	 * Resources contains all resources that are currently part of this stack after this deployment has finished.
	 */
	resources?: ResourceV2[];
	/**
	 * PendingOperations are all operations that were known by the engine to be currently executing.
	 */
	pending_operations?: OperationV1[];
}
/**
 * DeploymentV3 is the third version of the Deployment. It contains newer versions of the
 * Resource and Operation API types and a placeholder for a stack's secrets configuration.
 * Note that both deployment schema versions 3 and 4 can be unmarshaled into DeploymentV3.
 */
export interface DeploymentV3 {
	/**
	 * Manifest contains metadata about this deployment.
	 */
	manifest: ManifestV1;
	/**
	 * SecretsProviders is a placeholder for secret provider configuration.
	 */
	secrets_providers?: SecretsProvidersV1;
	/**
	 * Resources contains all resources that are currently part of this stack after this deployment has finished.
	 */
	resources?: ResourceV3[];
	/**
	 * PendingOperations are all operations that were known by the engine to be currently executing.
	 */
	pending_operations?: OperationV2[];
	/**
	 * Metadata associated with the snapshot.
	 */
	metadata?: SnapshotMetadataV1;
}
export interface SecretsProvidersV1 {
	type: string;
	state?: unknown;
}
/**
 * SnapshotMetadataV1 contains metadata about a deployment snapshot.
 */
export interface SnapshotMetadataV1 {
	/**
	 * Metadata associated with any integrity error affecting the snapshot.
	 */
	integrity_error?: SnapshotIntegrityErrorMetadataV1;
}
/**
 * SnapshotIntegrityErrorMetadataV1 contains metadata about a snapshot integrity error, such as the version
 * and invocation of the Pulumi engine that caused it.
 */
export interface SnapshotIntegrityErrorMetadataV1 {
	/**
	 * The version of the Pulumi engine that caused the integrity error.
	 */
	version?: string;
	/**
	 * The command/invocation of the Pulumi engine that caused the integrity error.
	 */
	command?: string;
	/**
	 * The error message associated with the integrity error.
	 */
	error?: string;
	/**
	 * EnvVars contains the Pulumi environment variables that were set when the integrity error occurred.
	 */
	env_vars?: { [key: string]: string};
}
/**
 * OperationType is the type of an operation initiated by the engine. Its value indicates the type of operation
 * that the engine initiated.
 */
/**
 * OperationTypeCreating is the state of resources that are being created.
 */
export const OperationTypeCreating = "creating";
/**
 * OperationTypeUpdating is the state of resources that are being updated.
 */
export const OperationTypeUpdating = "updating";
/**
 * OperationTypeDeleting is the state of resources that are being deleted.
 */
export const OperationTypeDeleting = "deleting";
/**
 * OperationTypeReading is the state of resources that are being read.
 */
export const OperationTypeReading = "reading";
export type OperationType = typeof OperationTypeCreating | typeof OperationTypeUpdating | typeof OperationTypeDeleting | typeof OperationTypeReading;
/**
 * OperationV1 represents an operation that the engine is performing. It consists of a Resource, which is the state
 * that the engine used to initiate the operation, and a Status, which is a string representation of the operation
 * that the engine initiated.
 */
export interface OperationV1 {
	/**
	 * Resource is the state that the engine used to initiate this operation.
	 */
	resource: ResourceV2;
	/**
	 * Status is a string representation of the operation that the engine is performing.
	 */
	type: OperationType;
}
/**
 * OperationV2 represents an operation that the engine is performing. It consists of a Resource, which is the state
 * that the engine used to initiate the operation, and a Status, which is a string representation of the operation
 * that the engine initiated.
 */
export interface OperationV2 {
	/**
	 * Resource is the state that the engine used to initiate this operation.
	 */
	resource: ResourceV3;
	/**
	 * Status is a string representation of the operation that the engine is performing.
	 */
	type: OperationType;
}
/**
 * UntypedDeployment contains an inner, untyped deployment structure.
 */
export interface UntypedDeployment {
	/**
	 * Version indicates the schema of the encoded deployment.
	 */
	version?: number /* int */;
	/**
	 * Features contains an optional list of features used by this deployment. The CLI will error when reading a
	 * Deployment that uses a feature that is not supported by that version of the CLI. This is only looked at
	 * when `Version` is 4 or greater.
	 */
	features?: string[];
	/**
	 * The opaque Pulumi deployment. This is conceptually of type `Deployment`, but we use `json.Message` to
	 * permit round-tripping of stack contents when an older client is talking to a newer server.  If we unmarshaled
	 * the contents, and then remarshaled them, we could end up losing important information.
	 */
	deployment?: unknown;
}
/**
 * TypedDeployment contains an inner, typed deployment structure.
 */
export interface TypedDeployment {
	/**
	 * Version indicates the schema of the encoded deployment.
	 */
	version?: number /* int */;
	/**
	 * Features contains an optional list of features used by this deployment. The CLI will error when reading a
	 * Deployment that uses a feature that is not supported by that version of the CLI. This is only looked at
	 * when `Version` is 4 or greater.
	 */
	features?: string[];
	/**
	 * The typed Pulumi deployment.
	 */
	deployment?: DeploymentV3;
}
/**
 * ResourceV1 describes a Cloud resource constructed by Pulumi.
 */
export interface ResourceV1 {
	/**
	 * URN uniquely identifying this resource.
	 */
	urn: string;
	/**
	 * Custom is true when it is managed by a plugin.
	 */
	custom: boolean;
	/**
	 * Delete is true when the resource should be deleted during the next update.
	 */
	delete?: boolean;
	/**
	 * ID is the provider-assigned resource, if any, for custom resources.
	 */
	id?: string;
	/**
	 * Type is the resource's full type token.
	 */
	type: string;
	/**
	 * Inputs are the input properties supplied to the provider.
	 */
	inputs?: { [key: string]: any};
	/**
	 * Defaults contains the default values supplied by the provider (DEPRECATED, see #637).
	 */
	defaults?: { [key: string]: any};
	/**
	 * Outputs are the output properties returned by the provider after provisioning.
	 */
	outputs?: { [key: string]: any};
	/**
	 * Parent is an optional parent URN if this resource is a child of it.
	 */
	parent?: string;
	/**
	 * Protect is set to true when this resource is "protected" and may not be deleted.
	 */
	protect?: boolean;
	/**
	 * Dependencies contains the dependency edges to other resources that this depends on.
	 */
	dependencies?: string[];
	/**
	 * InitErrors is the set of errors encountered in the process of initializing resource (i.e.,
	 * during create or update).
	 */
	initErrors?: string[];
}
/**
 * ResourceV2 is the second version of the Resource API type. It absorbs a few breaking changes:
 *  1. The deprecated `Defaults` field is removed because it is not used anywhere,
 *  2. It adds an additional bool field, "External", which reflects whether or not this resource
 *     exists because of a call to `ReadResource`. This is motivated by a need to store
 *     resources that Pulumi does not own in the deployment.
 *  3. It adds an additional string field, "Provider", that is a reference to a first-class provider
 *     associated with this resource.
 * Migrating from ResourceV1 to ResourceV2 involves:
 *  1. Dropping the `Defaults` field (it should be empty anyway)
 *  2. Setting the `External` field to "false", since a ResourceV1 existing for a resource
 *     implies that it is owned by Pulumi. Note that since this is the default value for
 *     booleans in Go, no explicit assignment needs to be made.
 *  3. Setting the "Provider" field to the empty string, because V1 deployments don't have first-class providers.
 */
export interface ResourceV2 {
	/**
	 * URN uniquely identifying this resource.
	 */
	urn: string;
	/**
	 * Custom is true when it is managed by a plugin.
	 */
	custom: boolean;
	/**
	 * Delete is true when the resource should be deleted during the next update.
	 */
	delete?: boolean;
	/**
	 * ID is the provider-assigned resource, if any, for custom resources.
	 */
	id?: string;
	/**
	 * Type is the resource's full type token.
	 */
	type: string;
	/**
	 * Inputs are the input properties supplied to the provider.
	 */
	inputs?: { [key: string]: any};
	/**
	 * Outputs are the output properties returned by the provider after provisioning.
	 */
	outputs?: { [key: string]: any};
	/**
	 * Parent is an optional parent URN if this resource is a child of it.
	 */
	parent?: string;
	/**
	 * Protect is set to true when this resource is "protected" and may not be deleted.
	 */
	protect?: boolean;
	/**
	 * External is set to true when the lifecycle of this resource is not managed by Pulumi.
	 */
	external?: boolean;
	/**
	 * Dependencies contains the dependency edges to other resources that this depends on.
	 */
	dependencies?: string[];
	/**
	 * InitErrors is the set of errors encountered in the process of initializing resource (i.e.,
	 * during create or update).
	 */
	initErrors?: string[];
	/**
	 * Provider is a reference to the provider that is associated with this resource.
	 */
	provider?: string;
}
/**
 * ResourceV3 is the third version of the Resource API type. It absorbs a few breaking changes:
 *  1. It adds a map from input property names to the dependencies that affect that input property. This is used to
 *     improve the precision of delete-before-create operations.
 *  2. It adds a new boolean field, `PendingReplacement`, that marks resources that have been deleted as part of a
 *     delete-before-create operation but have not yet been recreated.
 * Migrating from ResourceV2 to ResourceV3 involves:
 *  1. Populating the map from input property names to dependencies by assuming that every dependency listed in
 *     `Dependencies` affects every input property.
 */
export interface ResourceV3 {
	/**
	 * URN uniquely identifying this resource.
	 */
	urn: string;
	/**
	 * Custom is true when it is managed by a plugin.
	 */
	custom: boolean;
	/**
	 * Delete is true when the resource should be deleted during the next update.
	 */
	delete?: boolean;
	/**
	 * ID is the provider-assigned resource, if any, for custom resources.
	 */
	id?: string;
	/**
	 * Type is the resource's full type token.
	 */
	type: string;
	/**
	 * Inputs are the input properties supplied to the provider.
	 */
	inputs?: { [key: string]: any};
	/**
	 * Outputs are the output properties returned by the provider after provisioning.
	 */
	outputs?: { [key: string]: any};
	/**
	 * Parent is an optional parent URN if this resource is a child of it.
	 */
	parent?: string;
	/**
	 * Protect is set to true when this resource is "protected" and may not be deleted.
	 */
	protect?: boolean;
	/**
	 * Taint is set to true when we wish to force it to be replaced upon the next update.
	 */
	taint?: boolean;
	/**
	 * External is set to true when the lifecycle of this resource is not managed by Pulumi.
	 */
	external?: boolean;
	/**
	 * Dependencies contains the dependency edges to other resources that this depends on.
	 */
	dependencies?: string[];
	/**
	 * InitErrors is the set of errors encountered in the process of initializing resource (i.e.,
	 * during create or update).
	 */
	initErrors?: string[];
	/**
	 * Provider is a reference to the provider that is associated with this resource.
	 */
	provider?: string;
	/**
	 * PropertyDependencies maps from an input property name to the set of resources that property depends on.
	 */
	property_dependencies?: { [key: string]: string[]};
	/**
	 * PendingReplacement is used to track delete-before-replace resources that have been deleted but not yet
	 * recreated.
	 */
	pendingReplacement?: boolean;
	/**
	 * AdditionalSecretOutputs is a list of outputs that were explicitly marked as secret when the resource was created.
	 */
	additionalSecretOutputs?: string[];
	/**
	 * Aliases is a list of previous URNs that this resource may have had in previous deployments.
	 */
	aliases?: string[];
	/**
	 * CustomTimeouts is a configuration block that can be used to control timeouts of CRUD operations.
	 */
	customTimeouts?: { create?: string; update?: string; delete?: string };
	/**
	 * ImportID is the import input used for imported resources.
	 */
	importID?: string;
	/**
	 * If set to True, the providers Delete method will not be called for this resource. Pulumi simply stops tracking the deleted resource.
	 */
	retainOnDelete?: boolean;
	/**
	 * If set, the providers Delete method will not be called for this resource
	 * if specified resource is being deleted as well.
	 */
	deletedWith?: string;
	/**
	 * ReplaceWith is a list of resources whose replaces will also trigger this resource's replace.
	 */
	replaceWith?: string[];
	/**
	 * Created tracks when the remote resource was first added to state by pulumi. Checkpoints prior to early 2023 do not include this.
	 */
	created?: string;
	/**
	 * Modified tracks when the resource state was last altered. Checkpoints prior to early 2023 do not include this.
	 */
	modified?: string;
	/**
	 * SourcePosition tracks the source location of this resource's registration
	 */
	sourcePosition?: string;
	/**
	 * StackTrace records the stack at the time this resource was registered
	 */
	stackTrace?: StackFrameV1[];
	/**
	 * IgnoreChanges is a list of properties to ignore changes for.
	 */
	ignoreChanges?: string[];
	/**
	 * HideDiff is a list of properties to hide the diff for.
	 */
	hideDiff?: string[];
	/**
	 * ReplaceOnChanges is a list of properties that if changed trigger a replace.
	 */
	replaceOnChanges?: string[];
	/**
	 * If set, the engine will diff this with the last recorded value, and trigger a replace if they are not equal.
	 */
	replacementTrigger?: any;
	/**
	 * RefreshBeforeUpdate indicates that this resource should always be refreshed prior to updates.
	 */
	refreshBeforeUpdate?: boolean;
	/**
	 * ViewOf is a reference to the resource that this resource is a view of.
	 */
	viewOf?: string;
	/**
	 * ResourceHooks is a map of hook types to lists of hook names for the given type.
	 */
	resourceHooks?: { [key: string]: string[]};
}
/**
 * StackFrameV1 captures information about a stack frame.
 */
export interface StackFrameV1 {
	/**
	 * SourcePosition contains the source position associated with the stack frame.
	 */
	sourcePosition?: string;
}
/**
 * ManifestV1 captures meta-information about this checkpoint file, such as versions of binaries, etc.
 */
export interface ManifestV1 {
	/**
	 * Time of the update.
	 */
	time: string;
	/**
	 * Magic number, used to identify integrity of the checkpoint.
	 */
	magic: string;
	/**
	 * Version of the Pulumi engine used to render the checkpoint.
	 */
	version: string;
	/**
	 * Plugins contains the binary version info of plug-ins used.
	 */
	plugins?: PluginInfoV1[];
}
/**
 * PluginInfoV1 captures the version and information about a plugin.
 */
export interface PluginInfoV1 {
	name: string;
	path: string;
	type: PluginKind;
	version: string;
}
/**
 * SecretV1 captures the information that a particular value is secret and must be decrypted before use.
 * NOTE: nothing produces these values yet. This type is merely a placeholder for future use.
 */
export interface SecretV1 {
	'4dabf18193072939515e22adb298388d': string;
	ciphertext?: string;
	plaintext?: string;
}
/**
 * ConfigValue describes a single (possibly secret) configuration value.
 */
export interface ConfigValue {
	/**
	 * When Object is false: String is either the plaintext value (for non-secrets) or the base64-encoded ciphertext
	 * (for secrets). When Object is true: String is a JSON encoded object. If both Object and Secret are true, then the
	 * object contains at least one secure value. Secure values in an object are encoded as `{"secure":"ciphertext"}`
	 * where ciphertext is the base64-encoded ciphertext.
	 */
	string: string;
	/**
	 * Secret is true if this value is a secret and false otherwise.
	 */
	secret: boolean;
	/**
	 * Object is true if this value is a JSON encoded object.
	 */
	object: boolean;
}
/**
 * StackTagName is the key for the tags bag in stack. This is just a string, but we use a type alias to provide a richer
 * description of how the string is used in our apitype definitions.
 */
export type StackTagName = string;
/**
 * ProjectNameTag is a tag that represents the name of a project (coresponds to the `name` property of Pulumi.yaml).
 */
export const ProjectNameTag: StackTagName = "pulumi:project";
/**
 * ProjectRuntimeTag is a tag that represents the runtime of a project (the `runtime` property of Pulumi.yaml).
 */
export const ProjectRuntimeTag: StackTagName = "pulumi:runtime";
/**
 * ProjectDescriptionTag is a tag that represents the description of a project (Pulumi.yaml's `description`).
 */
export const ProjectDescriptionTag: StackTagName = "pulumi:description";
/**
 * ProjectTemplateTag is a tag that represents the template that was used to create a project.
 */
export const ProjectTemplateTag: StackTagName = "pulumi:template";
/**
 * VCSOwnerNameTag is a tag that represents the name of the owner on the cloud VCS that this stack
 * may be associated with (inferred by the CLI based on git remote info).
 */
export const VCSOwnerNameTag: StackTagName = "vcs:owner";
/**
 * VCSRepositoryNameTag is a tag that represents the name of a repository on the cloud VCS that this stack
 * may be associated with (inferred by the CLI based on git remote info).
 */
export const VCSRepositoryNameTag: StackTagName = "vcs:repo";
/**
 * VCSRepositoryKindTag is a tag that represents the kind of the cloud VCS that this stack
 * may be associated with (inferred by the CLI based on the git remote info).
 */
export const VCSRepositoryKindTag: StackTagName = "vcs:kind";
/**
 * VCSRepositoryRootTag is a tag that represents the root directory of the repository on the cloud VCS that
 * this stack may be associated with (pulled from git by the CLI)
 */
export const VCSRepositoryRootTag: StackTagName = "vcs:root";
/**
 * PulumiTagsConfigKey sets additional tags for a stack on a deployment. This is additive to any
 * tags that are already set on the stack.
 */
export const PulumiTagsConfigKey: string = "pulumi:tags";
/**
 * Stack describes a Stack running on a Pulumi Cloud.
 */
export interface Stack {
	/**
	 * ID is the logical ID of the stack.
	 * For maintainers of the Pulumi service:
	 * ID corresponds to the Program ID, not the Stack ID inside the Pulumi service.
	 */
	id: string;
	orgName: string;
	projectName: string;
	stackName: string;
	/**
	 * CurrentOperation provides information about a stack operation in-progress, as applicable.
	 */
	currentOperation?: OperationStatus;
	activeUpdate: string;
	tags?: { [key: StackTagName]: string};
	/**
	 * Optional cloud-persisted stack configuration.
	 * If set, then the stack's configuration is loaded from the cloud and not a file on disk.
	 */
	config?: StackConfig;
	version: number /* int */;
}
/**
 * StackConfig describes the configuration of a stack from Pulumi Cloud.
 */
export interface StackConfig {
	/**
	 * Reference to ESC environment to use as stack configuration.
	 */
	environment: string;
	/**
	 * SecretsProvider is this stack's secrets provider.
	 */
	secretsProvider?: string;
	/**
	 * EncryptedKey is the KMS-encrypted ciphertext for the data key used for secrets encryption.
	 * Only used for cloud-based secrets providers.
	 */
	encryptedKey?: string;
	/**
	 * EncryptionSalt is this stack's base64 encoded encryption salt. Only used for
	 * passphrase-based secrets providers.
	 */
	encryptionSalt?: string;
}
/**
 * OperationStatus describes the state of an operation being performed on a Pulumi stack.
 */
export interface OperationStatus {
	kind: UpdateKind;
	author: string;
	started: number /* int64 */;
}

//////////
// source: errors.go

/**
 * ErrorType is an enum for various types of common errors that occur.
 */
export type ErrorType = string;
/**
 * NotFoundErrorType is used when a resource or resource field was not found.
 * For example, updating a Stack that doesn't exist.
 */
export const NotFoundErrorType: ErrorType = "not_found";
/**
 * RequiredErrorType is used when a resource or resource field is missing and is required.
 * For example, creating a Stack without a project name.
 */
export const RequiredErrorType: ErrorType = "required";
/**
 * InvalidErrorType is used when the a resource or field was passed with an invalid value or state.
 * For example, creating a Stack with an invalid name.
 */
export const InvalidErrorType: ErrorType = "invalid";
/**
 * AlreadyExistsErrorType is used if the resource or field already exists (and must be unique).
 * For example, creating two Stacks with the same name.
 */
export const AlreadyExistsErrorType: ErrorType = "already_exists";
/**
 * CustomErrorType is used to describe any ErrorType not found in this file, and must be paired with
 * a custom error message.
 */
export const CustomErrorType: ErrorType = "custom";
/**
 * RequestError describes a request error in more detail, such the specific validation
 * error(s) that caused the request to fail and links to the relevant documentation.
 */
export interface RequestError {
	/**
	 * Resource is the user-friendly description of the resource, e.g. "stack" or "tag".
	 */
	resource: string;
	/**
	 * Attribute describes the property of the resource (if applicable) that is problematic, e.g.
	 * "name" or "length".
	 */
	attribute?: string;
	/**
	 * ErrorType is the type of error the attribute's value caused.
	 */
	errorType: ErrorType;
	/**
	 * CustomMessage is the error message to display with CustomErrorType.
	 */
	customMessage?: string;
}
/**
 * ErrorResponse is returned from the API when an actual response body is not appropriate. i.e.
 * in all error situations.
 */
export interface ErrorResponse {
	/**
	 * Code is the HTTP status code for the error response.
	 */
	code: number /* int */;
	/**
	 * Message is the user-facing message describing the error.
	 */
	message: string;
	/**
	 * DocumentationURL is an optional URL the user can to go learn more about the error.
	 */
	documentationUrl?: string;
	/**
	 * Errors optionally include more specific data about why the request failed.
	 */
	errors?: RequestError[];
}

//////////
// source: events.go

/**
 * CancelEvent is emitted when the user initiates a cancellation of the update in progress, or
 * the update successfully completes.
 */
export interface CancelEvent {
}
/**
 * StdoutEngineEvent is emitted whenever a generic message is written, for example warnings
 * from the pulumi CLI itself. Less common that DiagnosticEvent
 */
export interface StdoutEngineEvent {
	message: string;
	color: string;
}
/**
 * DiagnosticEvent is emitted whenever a diagnostic message is provided, for example errors from
 * a cloud resource provider while trying to create or update a resource.
 */
export interface DiagnosticEvent {
	urn?: string;
	prefix?: string;
	message: string;
	color: string;
	/**
	 * Severity is one of "info", "info#err", "warning", or "error".
	 */
	severity: string;
	streamID?: number /* int */;
	ephemeral?: boolean;
}
/**
 * StartDebuggingEvent is emitted to start a debugging session.
 */
export interface StartDebuggingEvent {
	config?: { [key: string]: any};
}
/**
 * PolicyEvent is emitted whenever there is Policy violation.
 */
export interface PolicyEvent {
	resourceUrn?: string;
	message: string;
	color: string;
	policyName: string;
	policyPackName: string;
	policyPackVersion: string;
	policyPackVersionTag: string;
	/**
	 * EnforcementLevel is one of "warning", "mandatory", "remediate", or "none".
	 */
	enforcementLevel: string;
	/**
	 * Severity is one of "low", "medium", "high", or "critical".
	 * An empty string is omitted and represents an unspecified severity.
	 */
	severity?: string;
}
/**
 * PolicyRemediationEvent is emitted whenever there is Policy transformation.
 */
export interface PolicyRemediationEvent {
	resourceUrn?: string;
	color: string;
	policyName: string;
	policyPackName: string;
	policyPackVersion: string;
	policyPackVersionTag: string;
	before?: { [key: string]: any};
	after?: { [key: string]: any};
}
/**
 * PolicyAnalyzeSummaryEvent is emitted after a call to Analyze on an analyzer, summarizing the results.
 */
export interface PolicyAnalyzeSummaryEvent {
	/**
	 * The URN of the resource being analyzed.
	 */
	resourceUrn: string;
	/**
	 * The name of the policy pack.
	 */
	policyPackName: string;
	/**
	 * The version of the policy pack.
	 */
	policyPackVersion: string;
	/**
	 * The version tag of the policy pack.
	 */
	policyPackVersionTag: string;
	/**
	 * The names of resource policies that passed (i.e. did not produce any violations).
	 */
	passed?: string[];
	/**
	 * The names of resource policies that failed (i.e. produced violations).
	 */
	failed?: string[];
}
/**
 * PolicyRemediateSummaryEvent is emitted after a call to Remediate on an analyzer, summarizing the results.
 */
export interface PolicyRemediateSummaryEvent {
	/**
	 * The URN of the resource being remediated.
	 */
	resourceUrn: string;
	/**
	 * The name of the policy pack.
	 */
	policyPackName: string;
	/**
	 * The version of the policy pack.
	 */
	policyPackVersion: string;
	/**
	 * The version tag of the policy pack.
	 */
	policyPackVersionTag: string;
	/**
	 * The names of resource policies that passed (i.e. did not produce any violations).
	 */
	passed?: string[];
	/**
	 * The names of resource policies that failed (i.e. produced violations).
	 */
	failed?: string[];
}
/**
 * PolicyAnalyzeStackSummaryEvent is emitted after a call to AnalyzeStack on an analyzer, summarizing the results.
 */
export interface PolicyAnalyzeStackSummaryEvent {
	/**
	 * The name of the policy pack.
	 */
	policyPackName: string;
	/**
	 * The version of the policy pack.
	 */
	policyPackVersion: string;
	/**
	 * The version tag of the policy pack.
	 */
	policyPackVersionTag: string;
	/**
	 * The names of stack policies that passed (i.e. did not produce any violations).
	 */
	passed?: string[];
	/**
	 * The names of stack policies that failed (i.e. produced violations).
	 */
	failed?: string[];
}
/**
 * PreludeEvent is emitted at the start of an update.
 */
export interface PreludeEvent {
	/**
	 * Config contains the keys and values for the update.
	 * Encrypted configuration values may be blinded.
	 */
	config: { [key: string]: string};
}
/**
 * SummaryEvent is emitted at the end of an update, with a summary of the changes made.
 */
export interface SummaryEvent {
	/**
	 * MaybeCorrupt is set if one or more of the resources is in an invalid state.
	 */
	maybeCorrupt: boolean;
	/**
	 * Duration is the number of seconds the update was executing.
	 */
	durationSeconds: number /* int */;
	/**
	 * ResourceChanges contains the count for resource change by type.
	 */
	resourceChanges: { [key: OpType]: number /* int */};
	/**
	 * PolicyPacks run during update. Maps PolicyPackName -> version.
	 * Note: When this field was initially added, we forgot to add the JSON tag
	 * and are now locked into to using PascalCase for this field to maintain backwards
	 * compatibility. For older clients this will map to the version, while for newer ones
	 * it will be the version tag prepended with "v".
	 */
	PolicyPacks: { [key: string]: string};
	/**
	 * IsPreview indicates whether this is a preview or an update.
	 */
	isPreview: boolean;
}
/**
 * ErrorEvent is emitted when an internal error occurs in the engine. This is not meant
 * to be used for user facing errors, but rather for internal errors, where an event
 * can help with debugging.
 */
export interface ErrorEvent {
	/**
	 * Error is the error message.
	 */
	error: string;
}
/**
 * DiffKind describes the kind of a particular property diff.
 */
export type DiffKind = string;
/**
 * DiffAdd indicates that the property was added.
 */
export const DiffAdd: DiffKind = "add";
/**
 * DiffAddReplace indicates that the property was added and requires that the resource be replaced.
 */
export const DiffAddReplace: DiffKind = "add-replace";
/**
 * DiffDelete indicates that the property was deleted.
 */
export const DiffDelete: DiffKind = "delete";
/**
 * DiffDeleteReplace indicates that the property was deleted and requires that the resource be replaced.
 */
export const DiffDeleteReplace: DiffKind = "delete-replace";
/**
 * DiffUpdate indicates that the property was updated.
 */
export const DiffUpdate: DiffKind = "update";
/**
 * DiffUpdateReplace indicates that the property was updated and requires that the resource be replaced.
 */
export const DiffUpdateReplace: DiffKind = "update-replace";
/**
 * PropertyDiff describes the difference between a single property's old and new values.
 */
export interface PropertyDiff {
	/**
	 * Kind is the kind of difference.
	 */
	diffKind: DiffKind;
	/**
	 * InputDiff is true if this is a difference between old and new inputs rather than old state and new inputs.
	 */
	inputDiff: boolean;
}
/**
 * StepEventMetadata describes a "step" within the Pulumi engine, which is any concrete action
 * to migrate a set of cloud resources from one state to another.
 */
export interface StepEventMetadata {
	/**
	 * Op is the operation being performed.
	 */
	op: OpType;
	urn: string;
	type: string;
	/**
	 * Old is the state of the resource before performing the step.
	 */
	old?: StepEventStateMetadata;
	/**
	 * New is the state of the resource after performing the step.
	 */
	new?: StepEventStateMetadata;
	/**
	 * Keys causing a replacement (only applicable for "create" and "replace" Ops).
	 */
	keys?: string[];
	/**
	 * Keys that changed with this step.
	 */
	diffs?: string[];
	/**
	 * The diff for this step as a list of property paths and difference types.
	 * NOTE: We don't want to omitempty this field because we want to distinguish between
	 * a nil value and an empty map. See https://github.com/pulumi/pulumi/pull/15213 for details.
	 */
	detailedDiff: { [key: string]: PropertyDiff};
	/**
	 * Logical is set if the step is a logical operation in the program.
	 */
	logical?: boolean;
	/**
	 * Provider actually performing the step.
	 */
	provider: string;
}
/**
 * StepEventStateMetadata is the more detailed state information for a resource as it relates to
 * a step(s) being performed.
 */
export interface StepEventStateMetadata {
	type: string;
	urn: string;
	/**
	 * Custom indicates if the resource is managed by a plugin.
	 */
	custom?: boolean;
	/**
	 * Delete is true when the resource is pending deletion due to a replacement.
	 */
	delete?: boolean;
	/**
	 * ID is the resource's unique ID, assigned by the resource provider (or blank if none/uncreated).
	 */
	id: string;
	/**
	 * Parent is an optional parent URN that this resource belongs to.
	 */
	parent: string;
	/**
	 * Protect is true to "protect" this resource (protected resources cannot be deleted).
	 */
	protect?: boolean;
	/**
	 * Taint is set to true when we wish to force it to be replaced upon the next update.
	 */
	taint?: boolean;
	/**
	 * RetainOnDelete is true if the resource is not physically deleted when it is logically deleted.
	 */
	retainOnDelete?: boolean;
	/**
	 * Inputs contains the resource's input properties (as specified by the program). Secrets have
	 * filtered out, and large assets have been replaced by hashes as applicable.
	 */
	inputs: { [key: string]: any};
	/**
	 * Outputs contains the resource's complete output state (as returned by the resource provider).
	 */
	outputs: { [key: string]: any};
	/**
	 * Provider is the resource's provider reference
	 */
	provider: string;
	/**
	 * InitErrors is the set of errors encountered in the process of initializing resource.
	 */
	initErrors?: string[];
	/**
	 * HideDiffs is the set of property paths where diffs are not displayed.
	 */
	hideDiffs?: string[];
}
/**
 * ResourcePreEvent is emitted before a resource is modified.
 */
export interface ResourcePreEvent {
	metadata: StepEventMetadata;
	planning?: boolean;
}
/**
 * ResOutputsEvent is emitted when a resource is finished being provisioned.
 */
export interface ResOutputsEvent {
	metadata: StepEventMetadata;
	planning?: boolean;
}
/**
 * ResOpFailedEvent is emitted when a resource operation fails. Typically a DiagnosticEvent is
 * emitted before this event, indicating the root cause of the error.
 */
export interface ResOpFailedEvent {
	metadata: StepEventMetadata;
	status: number /* int */;
	steps: number /* int */;
}
/**
 * PolicyLoadEvent is emitted when a policy starts loading
 */
export interface PolicyLoadEvent {
}
/**
 * ProgressEvent is emitted when a potentially long-running engine process is in
 * progress.
 */
export interface ProgressEvent {
	/**
	 * The type of process (e.g. plugin download, plugin install).
	 */
	type: ProgressType;
	/**
	 * A unique identifier for the process.
	 */
	id: string;
	/**
	 * A message accompanying the process.
	 */
	message: string;
	/**
	 * The number of items completed so far (e.g. bytes received, items installed,
	 * etc.)
	 */
	received: number /* int64 */;
	/**
	 * The total number of items that must be completed.
	 */
	total: number /* int64 */;
	/**
	 * True if and only if the process has completed.
	 */
	done: boolean;
}
/**
 * ProgressType is the type of process occurring.
 */
export type ProgressType = string;
/**
 * PluginDownload represents a download of a plugin.
 */
export const PluginDownload: ProgressType = "plugin-download";
/**
 * PluginInstall represents the installation of a plugin.
 */
export const PluginInstall: ProgressType = "plugin-install";
/**
 * EngineEvent describes a Pulumi engine event, such as a change to a resource or diagnostic
 * message. EngineEvent is a discriminated union of all possible event types, and exactly one
 * field will be non-nil.
 */
export interface EngineEvent {
	/**
	 * Sequence is a unique, and monotonically increasing number for each engine event sent to the
	 * Pulumi Service. Since events may be sent concurrently, and/or delayed via network routing,
	 * the sequence number is to ensure events can be placed into a total ordering.
	 * - No two events can have the same sequence number.
	 * - Events with a lower sequence number must have been emitted before those with a higher
	 *   sequence number.
	 */
	sequence: number /* int */;
	/**
	 * Timestamp is a Unix timestamp (seconds) of when the event was emitted.
	 */
	timestamp: number /* int */;
	cancelEvent?: CancelEvent;
	stdoutEvent?: StdoutEngineEvent;
	diagnosticEvent?: DiagnosticEvent;
	preludeEvent?: PreludeEvent;
	summaryEvent?: SummaryEvent;
	resourcePreEvent?: ResourcePreEvent;
	resOutputsEvent?: ResOutputsEvent;
	resOpFailedEvent?: ResOpFailedEvent;
	policyEvent?: PolicyEvent;
	policyRemediationEvent?: PolicyRemediationEvent;
	policyLoadEvent?: PolicyLoadEvent;
	policyAnalyzeSummaryEvent?: PolicyAnalyzeSummaryEvent;
	policyRemediateSummaryEvent?: PolicyRemediateSummaryEvent;
	policyAnalyzeStackSummaryEvent?: PolicyAnalyzeStackSummaryEvent;
	startDebuggingEvent?: StartDebuggingEvent;
	progressEvent?: ProgressEvent;
	errorEvent?: ErrorEvent;
}
/**
 * EngineEventBatch is a group of engine events.
 */
export interface EngineEventBatch {
	events: EngineEvent[];
}
/**
 * GetUpdateEventsResponse contains the engine events for an update.
 */
export interface GetUpdateEventsResponse {
	/**
	 * Events are returned sorted by their internal sequence number (not exposed to the API).
	 * So the last Event in the slice is the most recent event which was stored in the database.
	 * (Should sort identical to timestamp, but may not if we support parallel writes.)
	 */
	events: EngineEvent[];
	/**
	 * ContinuationToken is an opaque value the client can send to fetch more recent
	 * events if the update is still in progress. Will be nil once all events have
	 * been returned and the update is complete.
	 */
	continuationToken?: string;
}

//////////
// source: history.go

/**
 * UpdateKind is an enum for the type of update performed.
 * Should generally mirror backend.UpdateKind, but we clone it in this package to add
 * flexibility in case there is a breaking change in the backend-type.
 */
export type UpdateKind = string;
/**
 * UpdateUpdate is the prototypical Pulumi program update.
 */
export const UpdateUpdate: UpdateKind = "update";
/**
 * PreviewUpdate is a preview of an update, without impacting resources.
 */
export const PreviewUpdate: UpdateKind = "preview";
/**
 * RefreshUpdate is an update that came from a refresh operation.
 */
export const RefreshUpdate: UpdateKind = "refresh";
/**
 * RenameUpdate is an update that changes the stack name or project name of a Pulumi program.
 * NOTE: Do not remove this type - it is used by Pulumi Cloud code.
 */
export const RenameUpdate: UpdateKind = "rename";
/**
 * DestroyUpdate is an update which removes all resources.
 */
export const DestroyUpdate: UpdateKind = "destroy";
/**
 * StackImportUpdate is an update that entails importing a raw checkpoint file.
 */
export const StackImportUpdate: UpdateKind = "import";
/**
 * ResourceImportUpdate is an update that entails importing one or more resources.
 */
export const ResourceImportUpdate = "resource-import";
/**
 * UpdateResult is an enum for the result of the update.
 * Should generally mirror backend.UpdateResult, but we clone it in this package to add
 * flexibility in case there is a breaking change in the backend-type.
 */
export type UpdateResult = string;
/**
 * NotStartedResult is for updates that have not started.
 */
export const NotStartedResult: UpdateResult = "not-started";
/**
 * InProgressResult is for updates that have not yet completed.
 */
export const InProgressResult: UpdateResult = "in-progress";
/**
 * SucceededResult is for updates that completed successfully.
 */
export const SucceededResult: UpdateResult = "succeeded";
/**
 * FailedResult is for updates that have failed.
 */
export const FailedResult: UpdateResult = "failed";
/**
 * OpType describes the type of operation performed to a resource managed by Pulumi.
 * Should generally mirror deploy.StepOp, but we clone it in this package to add
 * flexibility in case there is a breaking change in the backend-type.
 */
export type OpType = string;
/**
 * OpSame indicates no change was made.
 */
export const OpSame: OpType = "same";
/**
 * OpCreate indicates a new resource was created.
 */
export const OpCreate: OpType = "create";
/**
 * OpUpdate indicates an existing resource was updated.
 */
export const OpUpdate: OpType = "update";
/**
 * OpDelete indicates an existing resource was deleted.
 */
export const OpDelete: OpType = "delete";
/**
 * OpReplace indicates an existing resource was replaced with a new one.
 */
export const OpReplace: OpType = "replace";
/**
 * OpCreateReplacement indicates a new resource was created for a replacement.
 */
export const OpCreateReplacement: OpType = "create-replacement";
/**
 * OpDeleteReplaced indicates an existing resource was deleted after replacement.
 */
export const OpDeleteReplaced: OpType = "delete-replaced";
/**
 * OpRead indicates reading an existing resource.
 */
export const OpRead: OpType = "read";
/**
 * OpReadReplacement indicates reading an existing resource for a replacement.
 */
export const OpReadReplacement: OpType = "read-replacement";
/**
 * OpRefresh indicates refreshing an existing resource.
 */
export const OpRefresh: OpType = "refresh"; // refreshing an existing resource.
/**
 * OpReadDiscard indicates removing a resource that was read.
 */
export const OpReadDiscard: OpType = "discard";
/**
 * OpDiscardReplaced indicates discarding a read resource that was replaced.
 */
export const OpDiscardReplaced: OpType = "discard-replaced";
/**
 * OpRemovePendingReplace indicates removing a pending replace resource.
 */
export const OpRemovePendingReplace: OpType = "remove-pending-replace";
/**
 * OpImport indicates importing an existing resource.
 */
export const OpImport: OpType = "import";
/**
 * OpImportReplacement indicates replacement of an existing resource with an imported resource.
 */
export const OpImportReplacement: OpType = "import-replacement";
/**
 * UpdateInfo describes a previous update.
 * Should generally mirror backend.UpdateInfo, but we clone it in this package to add
 * flexibility in case there is a breaking change in the backend-type.
 */
export interface UpdateInfo {
	/**
	 * Information known before an update is started.
	 */
	kind: UpdateKind;
	startTime: number /* int64 */;
	message: string;
	environment: { [key: string]: string};
	config: { [key: string]: ConfigValue};
	/**
	 * Information obtained from an update completing.
	 */
	result: UpdateResult;
	endTime: number /* int64 */;
	version: number /* int */;
	deployment?: unknown;
	resourceChanges?: { [key: OpType]: number /* int */};
	resourceCount?: number /* int */;
}
/**
 * GetHistoryResponse is the response from the Pulumi Service when requesting
 * a stack's history.
 */
export interface GetHistoryResponse {
	updates: UpdateInfo[];
}

//////////
// source: plugins.go
/*
Package apitype contains the full set of "exchange types" that are serialized and sent across separately versionable
boundaries, including service APIs, plugins, and file formats.  As a result, we must consider the versioning impacts
for each change we make to types within this package.  In general, this means the following:

 1. DO NOT take anything away
 2. DO NOT change processing rules
 3. DO NOT make optional things required
 4. DO make anything new be optional

In the event that this is not possible, a breaking change is implied.  The preferred approach is to never make
breaking changes.  If that isn't possible, the next best approach is to support both the old and new formats
side-by-side (for instance, by using a union type for the property in question).
*/

/**
 * apitype.PluginKind represents a kind of a plugin that may be dynamically loaded and used by Pulumi.
 * These are being re exported in sdk/go/common/workspace/plugins.go to keep backward compatibility and should
 * be kept in sync
 */
export type PluginKind = string;
/**
 * AnalyzerPlugin is a plugin that can be used as a resource analyzer.
 */
export const AnalyzerPlugin: PluginKind = "analyzer";
/**
 * LanguagePlugin is a plugin that can be used as a language host.
 */
export const LanguagePlugin: PluginKind = "language";
/**
 * ResourcePlugin is a plugin that can be used as a resource provider for custom CRUD operations.
 */
export const ResourcePlugin: PluginKind = "resource";
/**
 * ConverterPlugin is a plugin that can be used to convert from other ecosystems to Pulumi.
 */
export const ConverterPlugin: PluginKind = "converter";
/**
 * ToolPlugin is an arbitrary plugin that can be run as a tool.
 */
export const ToolPlugin: PluginKind = "tool";

//////////
// source: policy.go

/**
 * DefaultPolicyGroup is the name of the default Policy Group for organizations.
 */
export const DefaultPolicyGroup = "default-policy-group";
/**
 * CreatePolicyPackRequest defines the request body for creating a new Policy
 * Pack for an organization. The request contains the metadata related to the
 * Policy Pack.
 */
export interface CreatePolicyPackRequest {
	/**
	 * Name is a unique URL-safe identifier (at the org level) for the package.
	 * If the name has already been used by the organization, then the request will
	 * create a new version of the Policy Pack (incremented by one). This is supplied
	 * by the CLI.
	 */
	name: string;
	/**
	 * A pretty name for the Policy Pack that is supplied by the package.
	 */
	displayName: string;
	/**
	 * VersionTag is the semantic version of the Policy Pack. One a version is published, it
	 * cannot never be republished. Older clients will not have a version tag.
	 */
	versionTag?: string;
	/**
	 * The Policies outline the specific Policies in the package, and are derived
	 * from the package by the CLI.
	 */
	policies: Policy[];
	/**
	 * A brief description of the policy pack.
	 */
	description?: string;
	/**
	 * README text about the policy pack.
	 */
	readme?: string;
	/**
	 * The cloud provider/platform this policy pack is associated with, e.g. AWS, Azure, etc.
	 */
	provider?: string;
	/**
	 * Tags for this policy pack.
	 */
	tags?: string[];
	/**
	 * A URL to the repository where the policy pack is defined.
	 */
	repository?: string;
	/**
	 * Metadata contains optional data about the environment performing the publish operation,
	 * e.g. the current source code control commit information.
	 */
	metadata?: { [key: string]: string};
}
/**
 * CreatePolicyPackResponse is the response from creating a Policy Pack. It returns
 * a URI to upload the Policy Pack zip file to.
 */
export interface CreatePolicyPackResponse {
	version: number /* int */;
	uploadURI: string;
	/**
	 * RequiredHeaders represents headers that the CLI must set in order
	 * for the upload to succeed.
	 */
	requiredHeaders?: { [key: string]: string};
}
/**
 * RequiredPolicy is the information regarding a particular Policy that is required
 * by an organization.
 */
export interface RequiredPolicy {
	/**
	 * The name (unique and URL-safe) of the required Policy Pack.
	 */
	name: string;
	/**
	 * The version of the required Policy Pack.
	 */
	version: number /* int */;
	/**
	 * The version tag of the required Policy Pack.
	 */
	versionTag: string;
	/**
	 * The pretty name of the required Policy Pack.
	 */
	displayName: string;
	/**
	 * Where the Policy Pack can be downloaded from.
	 */
	packLocation?: string;
	/**
	 * The configuration that is to be passed to the Policy Pack. This is map a of policies
	 * mapped to their configuration. Each individual configuration must comply with the
	 * JSON schema for each Policy within the Policy Pack.
	 */
	config?: { [key: string]: unknown | undefined};
}
/**
 * Policy defines the metadata for an individual Policy within a Policy Pack.
 */
export interface Policy {
	/**
	 * Unique URL-safe name for the policy.  This is unique to a specific version
	 * of a Policy Pack.
	 */
	name: string;
	displayName: string;
	/**
	 * Description is used to provide more context about the purpose of the policy.
	 */
	description: string;
	enforcementLevel: EnforcementLevel;
	/**
	 * Message is the message that will be displayed to end users when they violate
	 * this policy.
	 */
	message: string;
	/**
	 * The JSON schema for the Policy's configuration.
	 */
	configSchema?: PolicyConfigSchema;
	/**
	 * The severity of the policy.
	 */
	severity?: PolicySeverity;
	/**
	 * The compliance framework that this policy belongs to.
	 */
	framework?: PolicyComplianceFramework;
	/**
	 * Tags associated with the policy.
	 */
	tags?: string[];
	/**
	 * A description of the steps to take to remediate a policy violation.
	 */
	remediationSteps?: string;
	/**
	 * A URL to more information about the policy.
	 */
	url?: string;
}
/**
 * PolicyConfigSchema defines the JSON schema of a particular Policy's
 * configuration.
 */
export interface PolicyConfigSchema {
	/**
	 * Config property name to JSON Schema map.
	 */
	properties?: { [key: string]: unknown | undefined};
	/**
	 * Required config properties.
	 */
	required?: string[];
	/**
	 * Type defines the data type allowed for the schema.
	 */
	type: JSONSchemaType;
}
/**
 * JSONSchemaType in an enum of allowed data types for a schema.
 */
export type JSONSchemaType = string;
/**
 * Object is a dictionary.
 */
export const Object: JSONSchemaType = "object";
/**
 * EnforcementLevel indicates how a policy should be enforced
 */
export type EnforcementLevel = string;
/**
 * Advisory is an enforcement level where the resource is still created, but a
 * message is displayed to the user for informational / warning purposes.
 */
export const Advisory: EnforcementLevel = "advisory";
/**
 * Mandatory is an enforcement level that prevents a resource from being created.
 */
export const Mandatory: EnforcementLevel = "mandatory";
/**
 * Remediate is an enforcement level that fixes policy issues instead of issuing diagnostics.
 */
export const Remediate: EnforcementLevel = "remediate";
/**
 * Disabled is an enforcement level that disables the policy from being enforced.
 */
export const Disabled: EnforcementLevel = "disabled";
/**
 * Indicates the severity of a policy.
 */
export const PolicySeverityUnspecified = "";
export const PolicySeverityLow = "low";
export const PolicySeverityMedium = "medium";
export const PolicySeverityHigh = "high";
export const PolicySeverityCritical = "critical";
export type PolicySeverity = typeof PolicySeverityUnspecified | typeof PolicySeverityLow | typeof PolicySeverityMedium | typeof PolicySeverityHigh | typeof PolicySeverityCritical;
/**
 * EntityType indicates the type of entity a policy group applies to
 */
export type EntityType = string;
/**
 * Stacks indicates the policy group applies to stacks
 */
export const Stacks: EntityType = "stacks";
/**
 * Accounts indicates the policy group applies to accounts
 */
export const Accounts: EntityType = "accounts";
/**
 * PolicyGroupMode indicates the enforcement mode of a policy group
 */
/**
 * PolicyGroupModePreventative enforces policies during pulumi up/preview operations,
 * potentially blocking resource changes when mandatory policies fail
 */
export const PolicyGroupModePreventative = "preventative";
/**
 * PolicyGroupModeAudit monitors resource compliance without blocking operations,
 * reporting policy violations for continuous compliance monitoring
 */
export const PolicyGroupModeAudit = "audit";
export type PolicyGroupMode = typeof PolicyGroupModePreventative | typeof PolicyGroupModeAudit;
/**
 * GetPolicyPackResponse is the response to get a specific Policy Pack's
 * metadata and policies.
 */
export interface GetPolicyPackResponse {
	name: string;
	displayName: string;
	version: number /* int */;
	versionTag: string;
	policies: Policy[];
	applied: boolean;
}
/**
 * GetStackPolicyPacksResponse is the response to getting the applicable Policy Packs
 * for a particular stack. This allows the CLI to download the packs prior to
 * starting an update.
 */
export interface GetStackPolicyPacksResponse {
	/**
	 * RequiredPolicies is a list of required Policy Packs to run during the update.
	 */
	requiredPolicies?: RequiredPolicy[];
}
/**
 * UpdatePolicyGroupRequest modifies a Policy Group.
 */
export interface UpdatePolicyGroupRequest {
	newName?: string;
	addStack?: PulumiStackReference;
	removeStack?: PulumiStackReference;
	addPolicyPack?: PolicyPackMetadata;
	removePolicyPack?: PolicyPackMetadata;
}
/**
 * PulumiStackReference contains the StackName and ProjectName of the stack.
 */
export interface PulumiStackReference {
	name: string;
	routingProject: string;
}
/**
 * PolicyPackMetadata is the metadata of a Policy Pack.
 */
export interface PolicyPackMetadata {
	name: string;
	displayName: string;
	version: number /* int */;
	versionTag: string;
	/**
	 * The configuration that is to be passed to the Policy Pack. This
	 * map ties Policies with their configuration.
	 */
	config?: { [key: string]: unknown | undefined};
}
/**
 * ListPolicyPacksResponse is the response to list an organization's
 * Policy Packs.
 */
export interface ListPolicyPacksResponse {
	policyPacks: PolicyPackWithVersions[];
}
/**
 * PolicyPackWithVersions details the specifics of a Policy Pack and all its available versions.
 */
export interface PolicyPackWithVersions {
	name: string;
	displayName: string;
	versions: number /* int */[];
	versionTags: string[];
}
/**
 * ListPolicyGroupsResponse lists a summary of the organization's Policy Groups.
 */
export interface ListPolicyGroupsResponse {
	policyGroups: PolicyGroupSummary[];
}
/**
 * PolicyGroupSummary details the name, applicable stacks and the applied Policy
 * Packs for an organization's Policy Group.
 */
export interface PolicyGroupSummary {
	name: string;
	isOrgDefault: boolean;
	numStacks: number /* int */;
	numAccounts?: number /* int */;
	entityType: EntityType;
	mode: PolicyGroupMode;
	numEnabledPolicyPacks: number /* int */;
}
/**
 * GetPolicyPackConfigSchemaResponse is the response that includes the JSON
 * schemas of Policies within a particular Policy Pack.
 */
export interface GetPolicyPackConfigSchemaResponse {
	/**
	 * The JSON schema for each Policy's configuration.
	 */
	configSchema?: { [key: string]: PolicyConfigSchema};
}
/**
 * PolicyComplianceFramework represents a compliance framework that a policy belongs to.
 */
export interface PolicyComplianceFramework {
	/**
	 * The compliance framework name.
	 */
	name?: string;
	/**
	 * The compliance framework version.
	 */
	version?: string;
	/**
	 * The compliance framework reference.
	 */
	reference?: string;
	/**
	 * The compliance framework specification.
	 */
	specification?: string;
}

//////////
// source: service.go

/**
 * An APICapability is the name of a capability or feature that a service backend
 * may or may not support.
 */
export type APICapability = string;
/**
 * Deprecated. Use DeltaCheckpointUploadsV2.
 */
export const DeltaCheckpointUploads: APICapability = "delta-checkpoint-uploads";
/**
 * DeltaCheckpointUploads is the feature that enables the CLI to upload checkpoints
 * via the PatchUpdateCheckpointDeltaRequest API to save on network bytes.
 */
export const DeltaCheckpointUploadsV2: APICapability = "delta-checkpoint-uploads-v2";
/**
 * Indicates that the service backend supports batch encryption.
 */
export const BatchEncrypt: APICapability = "batch-encrypt";
/**
 * Indicates whether the service supports summarizing errors via Copilot.
 */
export const CopilotSummarizeError: APICapability = "copilot-summarize-error";
/**
 * Indicates whether the service supports the Copilot explainer.
 */
export const CopilotExplainPreview: APICapability = "copilot-explain-preview";
/**
 * Indicates the maximum deployment schema version that the service supports.
 */
export const DeploymentSchemaVersion: APICapability = "deployment-schema-version";
/**
 * Indicates whether the service supports retrieving a stack's required policy packs.
 */
export const StackPolicyPacks: APICapability = "stack-policy-packs";
export interface DeltaCheckpointUploadsConfigV2 {
	/**
	 * CheckpointCutoffSizeBytes defines the size of a checkpoint file, in bytes,
	 * at which the CLI should cutover to using delta checkpoint uploads.
	 */
	checkpointCutoffSizeBytes: number /* int */;
}
/**
 * DeploymentSchemaVersionConfig is the configuration for the deployment-schema-version capability.
 */
export interface DeploymentSchemaVersionConfig {
	/**
	 * Version is the maximum version of the deployment schema that the service supports.
	 */
	version: number /* int */;
}
/**
 * APICapabilityConfig captures a service backend capability and any associated
 * configuration that may be required for integration.
 */
export interface APICapabilityConfig {
	capability: APICapability;
	version?: number /* int */;
	configuration?: unknown;
}
/**
 * CapabilitiesResponse defines all feature sets that are available in the service
 * backend and are therefore available for the CLI to integrate against.
 */
export interface CapabilitiesResponse {
	capabilities: APICapabilityConfig[];
}
/**
 * Represents the set of features a backend is capable of supporting.
 * This is a user-friendly representation of the CapabilitiesResponse.
 */
export interface Capabilities {
	/**
	 * If non-nil, indicates that delta checkpoint updates are supported.
	 */
	DeltaCheckpointUpdates?: DeltaCheckpointUploadsConfigV2;
	/**
	 * Indicates whether the service supports batch encryption.
	 */
	BatchEncryption: boolean;
	/**
	 * Indicates whether the service supports summarizing errors via Copilot.
	 */
	CopilotSummarizeErrorV1: boolean;
	/**
	 * Indicates whether the service supports the Copilot explainer.
	 */
	CopilotExplainPreviewV1: boolean;
	/**
	 * Indicates the maximum deployment schema version that the service supports.
	 */
	DeploymentSchemaVersion: number /* int */;
	/**
	 * Indicates whether the service supports retrieving a stack's required policy packs.
	 */
	StackPolicyPacks: boolean;
}

//////////
// source: stacks.go

/**
 * StackSummary describes the state of a stack, without including its specific resources, etc.
 */
export interface StackSummary {
	/**
	 * ID is the logical ID of the stack.
	 * For maintainers of the Pulumi service:
	 * ID corresponds to the Program ID, not the Stack ID inside the Pulumi service.
	 */
	id: string;
	/**
	 * OrgName is the organization name the stack is found in.
	 */
	orgName: string;
	/**
	 * ProjectName is the name of the project the stack is associated with.
	 */
	projectName: string;
	/**
	 * StackName is the name of the stack.
	 */
	stackName: string;
	/**
	 * LastUpdate is a Unix timestamp of the start time of the stack's last update, as applicable.
	 */
	lastUpdate?: number /* int64 */;
	/**
	 * ResourceCount is the number of resources associated with this stack, as applicable.
	 */
	resourceCount?: number /* int */;
	/**
	 * Links to the stack in the Pulumi Console
	 */
	links?: StackLinks;
}
export interface StackLinks {
	self: string;
}
/**
 * ListStacksResponse returns a set of stack summaries. This call is designed to be inexpensive.
 */
export interface ListStacksResponse {
	stacks: StackSummary[];
	/**
	 * ContinuationToken is an opaque value used to mark the end of the all stacks. If non-nil,
	 * pass it into a subsequent call in order to get the next batch of results.
	 * A value of nil means that all stacks have been returned.
	 */
	continuationToken?: string;
}
/**
 * CreateStackRequest defines the request body for creating a new Stack
 */
export interface CreateStackRequest {
	/**
	 * The rest of the StackIdentifier (e.g. organization, project) is in the URL.
	 */
	stackName: string;
	/**
	 * An optional set of tags to apply to the stack.
	 */
	tags?: { [key: StackTagName]: string};
	/**
	 * An optional set of teams to assign to the stack.
	 */
	teams?: string[];
	/**
	 * An optional state to initialize the stack with.
	 */
	state?: UntypedDeployment;
	config?: StackConfig;
}
/**
 * CreateStackResponse is the response from a create Stack request.
 */
export interface CreateStackResponse {
}
/**
 * EncryptValueRequest defines the request body for encrypting a value.
 */
export interface EncryptValueRequest {
	/**
	 * The value to encrypt.
	 */
	plaintext: string /* []byte */;
}
/**
 * EncryptValueResponse defines the response body for an encrypted value.
 */
export interface EncryptValueResponse {
	/**
	 * The encrypted value.
	 */
	ciphertext: string /* []byte */;
}
/**
 * BatchEncryptRequest defines the request body for encrypting multiple values.
 */
export interface BatchEncryptRequest {
	/**
	 * The values to encrypt.
	 */
	plaintexts: string /* []byte */[];
}
/**
 * BatchEncryptResponse defines the response body for multiple encrypted values.
 */
export interface BatchEncryptResponse {
	/**
	 * The encrypted values, in order of the plaintexts from the request.
	 */
	ciphertexts: string /* []byte */[];
}
/**
 * DecryptValueRequest defines the request body for decrypting a value.
 */
export interface DecryptValueRequest {
	/**
	 * The value to decrypt.
	 */
	ciphertext: string /* []byte */;
}
/**
 * DecryptValueResponse defines the response body for a decrypted value.
 */
export interface DecryptValueResponse {
	/**
	 * The decrypted value.
	 */
	plaintext: string /* []byte */;
}
/**
 * Log3rdPartyDecryptionEvent defines the request body for logging a 3rd party secrets provider decryption event.
 */
export interface Log3rdPartyDecryptionEvent {
	secretName?: string;
	commandName?: string;
}
/**
 * BatchDecryptRequest defines the request body for batch decrypting secret values.
 */
export interface BatchDecryptRequest {
	ciphertexts: string /* []byte */[];
}
/**
 * BatchDecryptResponse defines the response body for batch decrypted secret values. The key in
 * the map is the base64 encoding of the ciphertext.
 */
export interface BatchDecryptResponse {
	plaintexts: { [key: string]: string /* []byte */};
}
/**
 * ExportStackResponse defines the response body for exporting a Stack.
 */
export type ExportStackResponse = UntypedDeployment;
/**
 * ImportStackRequest defines the request body for importing a Stack.
 */
export type ImportStackRequest = UntypedDeployment;
/**
 * ImportStackResponse defines the response body for importing a Stack.
 */
export interface ImportStackResponse {
	updateId: string;
}

//////////
// source: updates.go

/**
 * CreateUpdateConfig describes the configuration data for an request to `POST /updates`.
 */
export interface CreateUpdateConfig {
	/**
	 * Contents contains the configuration values for an update as a set of key-value pairs.
	 */
	contents: { [key: string]: ConfigValue};
}
/**
 * UpdateProgramRequest is the request type for updating (aka deploying) a Pulumi program.
 */
export interface UpdateProgramRequest {
	/**
	 * Properties from the Project file. Subset of pack.Package.
	 */
	name: string;
	runtime: string;
	main: string;
	description: string;
	options: UpdateOptions;
	/**
	 * Configuration values.
	 */
	config: { [key: string]: ConfigValue};
	metadata: UpdateMetadata;
}
/**
 * UpdateOptions is the set of operations for configuring the output of an update.
 * Should generally mirror engine.UpdateOptions, but we clone it in this package to add
 * flexibility in case there is a breaking change in the engine-type.
 */
export interface UpdateOptions {
	localPolicyPackPaths: string[];
	color: string;
	dryRun: boolean;
	parallel: number /* int32 */;
	showConfig: boolean;
	showReplacementSteps: boolean;
	showNames: boolean;
	summary: boolean;
	debug: boolean;
}
/**
 * UpdateMetadata describes optional metadata about an update.
 * Should generally mirror backend.UpdateMetadata, but we clone it in this package to add
 * flexibility in case there is a breaking change in the backend-type.
 */
export interface UpdateMetadata {
	/**
	 * Message is an optional message associated with the update.
	 */
	message: string;
	/**
	 * Environment contains optional data from the deploying environment. e.g. the current
	 * source code control commit information.
	 */
	environment: { [key: string]: string};
}
/**
 * EscEnvironmentMetadata describes the ESC Environments used in an update.
 */
export interface EscEnvironmentMetadata {
	/**
	 * This will be in the format of "[project/]name[@tag/version]"
	 */
	id: string;
}
export const MessageSeverityWarning = "warning";
export const MessageSeverityError = "error";
export const MessageSeverityInfo = "info";
export type MessageSeverity = typeof MessageSeverityWarning | typeof MessageSeverityError | typeof MessageSeverityInfo;
/**
 * Message is a message from the backend to be displayed to the user.
 */
export interface Message {
	/**
	 * Severity is the severity of the message.
	 */
	severity?: MessageSeverity;
	/**
	 * Message is the message to display to the user.
	 */
	message: string;
}
export interface AISettingsForUpdate {
	copilotIsEnabled: boolean;
}
/**
 * UpdateProgramResponse is the result of an update program request.
 */
export interface UpdateProgramResponse {
	/**
	 * UpdateID is the opaque identifier of the requested update. This value is needed to begin an update, as
	 * well as poll for its progress.
	 */
	updateID: string;
	/**
	 * RequiredPolicies is a list of required Policy Packs to run during the update.
	 */
	requiredPolicies?: RequiredPolicy[];
	/**
	 * Messages is a list of messages that should be displayed to the user.
	 */
	messages?: Message[];
	aiSettings?: AISettingsForUpdate;
}
/**
 * StartUpdateRequest requests that an update starts getting applied to a stack.
 */
export interface StartUpdateRequest {
	/**
	 * Tags contains an updated set of Tags for the stack. If non-nil, will replace the current
	 * set of tags associated with the stack.
	 */
	tags?: { [key: StackTagName]: string};
	/**
	 * JournalVersion indicates the maximum journal version the client supports.  If 0, journaling
	 * is not supported.
	 */
	journalVersion?: number /* int64 */;
}
/**
 * StartUpdateResponse is the result of the command to start an update.
 */
export interface StartUpdateResponse {
	/**
	 * Version is the version of the program once the update is complete.
	 * (Will be the current, unchanged value for previews.)
	 */
	version: number /* int */;
	/**
	 * Token is the lease token (if any) to be used to authorize operations on this update.
	 */
	token?: string;
	/**
	 * TokenExpiration is a UNIX timestamp by which the token will expire.
	 */
	tokenExpiration?: number /* int64 */;
	/**
	 * JournalVersion indicates the maximum version of journal entries that should be
	 * sent to the server. Is expected to be less or equal than the JournalVersion we
	 * sent in the update request.  If 0, journaling is disabled.
	 */
	journalVersion?: number /* int64 */;
}
/**
 * UpdateEventKind is an enum for the type of update events.
 */
export type UpdateEventKind = string;
/**
 * StdoutEvent is used to mark the event being emitted to STDOUT.
 */
export const StdoutEvent: UpdateEventKind = "stdout";
/**
 * StderrEvent is used to mark the event being emitted to STDERR.
 */
export const StderrEvent: UpdateEventKind = "stderr";
/**
 * UpdateEvent describes an event that happened on the Pulumi Cloud while processing an update.
 */
export interface UpdateEvent {
	index: string;
	kind: UpdateEventKind;
	fields: { [key: string]: any};
}
/**
 * UpdateStatus is an enum describing the current state during the lifecycle of an update.
 */
/**
 * StatusNotStarted is returned when the Update has been created but not applied.
 */
export const StatusNotStarted: UpdateStatus = "not started";
/**
 * StatusRequested is returned when the Update application has been requested but not started.
 */
export const StatusRequested: UpdateStatus = "requested";
/**
 * StatusRunning is returned when the Update is in progress.
 */
export const StatusRunning: UpdateStatus = "running";
/**
 * StatusFailed is returned when the update has failed.
 */
export const StatusFailed: UpdateStatus = "failed";
/**
 * StatusSucceeded is returned when the update has succeeded.
 */
export const StatusSucceeded: UpdateStatus = "succeeded";
/**
 * UpdateResults returns a series of events and the current status of an update. The events can be filtered. See
 * API call for more details.
 */
export interface UpdateResults {
	status: UpdateStatus;
	events: UpdateEvent[];
	/**
	 * ContinuationToken is an opaque value used to indiciate the end of the returned update
	 * results. Pass it in the next request to obtain subsequent update events.
	 * The same continuation token may be returned if no new update events are available, but the
	 * update is still in-progress.
	 * A value of nil means that no new updates will be available. Everything has been returned to
	 * the client and the update has completed.
	 */
	continuationToken?: string;
}
/**
 * UpdateProgram describes the metadata associated with an update's Pulumi program. Note that this does not
 * include the contents of the program itself.
 */
export interface UpdateProgram {
	/**
	 * Name is the name of the program.
	 */
	name: string;
	/**
	 * Runtime is the language runtime used to execute the program.
	 */
	runtime: string;
	/**
	 * Main is an optional redirect for the main program location. (e.g. a subfolder under Pulumi.yaml
	 * containing package.json.)
	 */
	main: string;
	/**
	 * Analyzers is the set of analyzers to run when this program is executed.
	 */
	analyzers: string[];
	/**
	 * Destroy indicates whether or not this program is the nil program (i.e. the program that generates no resources).
	 */
	destroy: boolean;
	/**
	 * Refresh is true if this is a refresh-style update, which simply takes state from the current cloud resources.
	 */
	refresh: boolean;
}
/**
 * RenewUpdateLeaseRequest defines the body of a request to the update lease renewal endpoint of the service API.
 */
export interface RenewUpdateLeaseRequest {
	/**
	 * The current, valid lease token.
	 * DEPRECATED as of Pulumi API version 5+. Pulumi API will expect the update token
	 * in the Authorization header instead of this property. This property will be removed
	 * when the minimum supported API version on the service is raised to 5.
	 */
	token: string;
	/**
	 * The duration for which to renew the lease in seconds (maximum 300).
	 */
	duration: number /* int */;
}
/**
 * RenewUpdateLeaseResponse defines the data returned by the update lease renewal endpoint of the service API.
 */
export interface RenewUpdateLeaseResponse {
	/**
	 * The renewed token.
	 */
	token: string;
	/**
	 * TokenExpiration is a UNIX timestamp by which the token will expire.
	 */
	tokenExpiration?: number /* int64 */;
}
/**
 * UpdateStatusSucceeded indicates that an update completed successfully.
 */
export const UpdateStatusSucceeded = "succeeded";
/**
 * UpdateStatusFailed indicates that an update completed with one or more failures.
 */
export const UpdateStatusFailed = "failed";
/**
 * UpdateStatusCancelled indicates that an update completed due to cancellation.
 */
export const UpdateStatusCancelled = "cancelled";
export type UpdateStatus = string;
/**
 * CompleteUpdateRequest defines the body of a request to the update completion endpoint of the service API.
 */
export interface CompleteUpdateRequest {
	status: UpdateStatus;
}
/**
 * PatchUpdateCheckpointRequest defines the body of a request to the patch update checkpoint endpoint of the service
 * API. The `Deployment` field is expected to contain a serialized `Deployment` value, the schema of which is indicated
 * by the `Version` field.
 */
export interface PatchUpdateCheckpointRequest {
	isInvalid: boolean;
	version: number /* int */;
	features?: string[];
	deployment?: unknown;
}
/**
 * PatchUpdateVerbatimCheckpointRequest defines the body of a request to a patch update checkpoint endpoint of the
 * service API, where `UntypedDeloyment` is an `apitype.UntypedDeployment`. Whereas the PatchUpdateCheckpointRequest
 * API is subject to the service reformatting how a checkpoint is persisted, PatchUpdateVerbatimCheckpointRequest
 * enables the CLI to define the exact format.
 * Designed to be compatible with the PatchUpdateCheckpointDeltaRequest API, where formatting is critical in calculating
 * textual diffs.
 */
export interface PatchUpdateVerbatimCheckpointRequest {
	version: number /* int */;
	untypedDeployment?: unknown;
	/**
	 * Idempotency key incremented by the client on every PATCH call within the same update.
	 */
	sequenceNumber: number /* int */;
}
/**
 * PatchUpdateCheckpointDeltaRequest defines the body of a request to the bandwidth-optimized version of the patch
 * update checkpoint endpoint of the service API. It is semantically equivalent to the PatchUpdateCheckpointRequest, but
 * instead of transferring the entire Deployment as a JSON blob, it encodes it as a textual diff against the last-saved
 * deployment. This conserves bandwidth on large resources.
 */
export interface PatchUpdateCheckpointDeltaRequest {
	/**
	 * Protocol version.
	 */
	version: number /* int */;
	/**
	 * SHA256 hash of the result of aplying the DeploymentDelta to the previously saved deployment.
	 */
	checkpointHash: string;
	/**
	 * Idempotency key incremented by the client on every PATCH call within the same update.
	 */
	sequenceNumber: number /* int */;
	/**
	 * Textual diff that recovers the desired deployment JSON when applied to the previously saved deployment JSON.
	 */
	deploymentDelta?: unknown;
}
/**
 * AppendUpdateLogEntryRequest defines the body of a request to the append update log entry endpoint of the service API.
 * No longer sent from the CLI, but the type definition is still required for backwards compat with older clients.
 */
export interface AppendUpdateLogEntryRequest {
	kind: string;
	fields: { [key: string]: any};
}
/**
 * StackRenameRequest is the shape of the request to change an existing stack's name.
 * If either NewName or NewProject is the empty string, the current project/name will
 * be preserved. (But at least one should be set.)
 */
export interface StackRenameRequest {
	newName: string;
	newProject: string;
}
