name: Deploy Dev

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-dev
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy-sst.yml
    permissions:
      id-token: write
      contents: read
    with:
      stage: dev
      environment: dev
    secrets: inherit
